### PR TITLE
Fix try runtime

### PR DESCRIPTION
**Pull request by Szegoo**
Building with `features try-runtime` was failing since the ismp pallets did not have the try-runtime feature.

### CODE REVIEW

**Review by seunlanlege — APPROVED** [review]
Interesting, what's `try-runtime` useful for?

**Comment by Szegoo** [comment]
> Interesting, what's `try-runtime` useful for?

https://paritytech.github.io/try-runtime-cli/try_runtime/

**Comment by seunlanlege** [comment]
> https://paritytech.github.io/try-runtime-cli/try_runtime/

I see, we just use [`polytope-labs/sc-simnode`](https://github.com/polytope-labs/sc-simnode) instead.

**Comment by Szegoo** [comment]
> I see, we just use [`polytope-labs/sc-simnode`](https://github.com/polytope-labs/sc-simnode) instead.

Will look into it. I wanted to use `try-runtime` in the RegionX parachain for testing runtime upgrades, but this could also be an interesting alternative.

**Pull request merged**
